"-- Decompiled with the Synapse X Luau decompiler.

return"{
   MHAPASS2023JAN ={
      Timer = 466416,
      Start = 465216,
      "FreeRewards ="{
         "Deku (airforce)",
         "Gold",
         "Gems",
         "Gems",
         "Gold",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "EXP II",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Madoka",
         "Gold",
         "Tickets",
         "Gems",
         "Stardust",
         "Gold",
         "Sand Capsule",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "EXP IV",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Tickets",
         "Gems",
         "Sand Capsule",
         "Stardust",
         "Gold",
         "Stardust",
         "Gems",
         "Stardust",
         "DekuEvolve",
         "Gold",
         "Gold",
         "Gems",
         "Gold",
         "Sand Capsule",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Gold",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Tickets",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Gold",
         "Gold",
         "Stardust",
         "Sand Capsule",
         "Gems",
         "Gold",
         "Gems",
         "Gems",
         "Gems",
         "Gems",
         "Stardust",
         "EXP IV",
         "Gold",
         "Gems",
         "Gems",
         "DekuEvolve1"
      },
      "PaidRewards ="{
         "Shigaraki5",
         "Gems",
         "Stardust",
         "Sand Capsule",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "Gold",
         "Tickets",
         "Gems",
         "Gold",
         "Gems",
         "Gems",
         "Gold",
         "Gems",
         "EXP II",
         "Gold",
         "Gems",
         "Sand Capsule",
         "Gems",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Tickets",
         "Gems",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "Mina",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Sand Capsule",
         "Gems",
         "EXP III",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gold",
         "Gems",
         "Stardust",
         "HandEvolve",
         "Tickets",
         "Gems",
         "Gold",
         "Gold",
         "Gems",
         "Gems",
         "Sand Capsule",
         "Gems",
         "EXP IV",
         "Gold",
         "Gold",
         "Gems",
         "Gems",
         "Sand Capsule",
         "Diane",
         "Stardust",
         "Gems",
         "Gems",
         "Gold",
         "Sand Capsule",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Sand Capsule",
         "Gold",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "EXP IV",
         "Gems",
         "Madoka Orb",
         "Gems",
         "Gold",
         "Gold",
         "Gems",
         "Gems",
         "Gems",
         "Gold",
         "Stardust",
         "Sand Capsule",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "HandEvolve"
      }
   },
   "NarutoBPOctober ="{
      Timer = 464321,
      Start = 462912,
      "FreeRewards ="{
         "Naruto StarPass5",
         "Gold",
         "Gems",
         "Gems",
         "Gold",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "EXP II",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Wammu",
         "Gold",
         "Tickets",
         "Gems",
         "Stardust",
         "Gold",
         "Sand Capsule",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "EXP III",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Tickets",
         "Gems",
         "Sand Capsule",
         "Stardust",
         "Gold",
         "Stardust",
         "Gems",
         "Stardust",
         "TailedEvolve",
         "Gold",
         "Gold",
         "Gems",
         "Gold",
         "Sand Capsule",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Gold",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Tickets",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Gold",
         "Gold",
         "Stardust",
         "Sand Capsule",
         "Gems",
         "Gold",
         "TailedEvolve2",
         "Gems",
         "Gems",
         "Gems",
         "Stardust",
         "EXP IV",
         "Gold",
         "Gems",
         "Gems",
         "Controled Beast Variant Orb"
      },
      "PaidRewards ="{
         "Sasuke StarPass5",
         "Gems",
         "Stardust",
         "Sand Capsule",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "Gold",
         "Tickets",
         "Gems",
         "Gold",
         "Gems",
         "Gems",
         "Gold",
         "Gems",
         "EXP II",
         "Gold",
         "Gems",
         "Sand Capsule",
         "Gems",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Tickets",
         "Gems",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Sand Capsule",
         "Gems",
         "EXP III",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gold",
         "Gems",
         "Stardust",
         "SamuraiEvolve",
         "Tickets",
         "Gems",
         "Gold",
         "",
         "Gems",
         "Gems",
         "Sand Capsule",
         "Gems",
         "EXP IV",
         "Gold",
         "Gold",
         "Gems",
         "Gems",
         "Sand Capsule",
         "Sengoku",
         "Stardust",
         "Gems",
         "Gems",
         "Gold",
         "Sand Capsule",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Sand Capsule",
         "Gold",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "EXP IV",
         "Gems",
         "",
         "Gems",
         "Gold",
         "Gold",
         "Gems",
         "SamuraiEvolve2",
         "Gems",
         "Gold",
         "Stardust",
         "Sand Capsule",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "Controled Samurai Variant Orb"
      }
   },
   "JulyTwentyTwo ="{
      Timer = 464101,
      Start = 462912,
      "FreeRewards ="{
         "Gold",
         "Gold",
         "Gems",
         "Gems",
         "Gold",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "EXP II",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Gold",
         "Gold",
         "Tickets",
         "Gems",
         "Stardust",
         "Gold",
         "Flower Capsule",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "EXP III",
         "Prometheus",
         "Gems",
         "Gold",
         "Gems",
         "Tickets",
         "Gems",
         "Flower Capsule",
         "Stardust",
         "Gold",
         "Stardust",
         "Gems",
         "Stardust",
         "Gems",
         "Gold",
         "Grey Skyden",
         "Gems",
         "Gold",
         "Flower Capsule",
         "Gems",
         "Tickets",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Gold",
         "Flower Capsule",
         "Gems",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Mop",
         "Gems",
         "Tickets",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Rayleigh",
         "Gold",
         "Stardust",
         "Flower Capsule",
         "Gems",
         "Gold",
         "Stardust",
         "Gems",
         "Gems",
         "Gems",
         "Stardust",
         "EXP IV",
         "Gold",
         "Gems",
         "Gems",
         "Whitebeard (Prime)"
      },
      "PaidRewards ="{
         "ZEUS",
         "Gems",
         "Stardust",
         "Flower Capsule",
         "Gold",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "Gold",
         "Tickets",
         "Gems",
         "Gold",
         "Gems",
         "Gems",
         "Gold",
         "Gems",
         "EXP II",
         "Gold",
         "Gems",
         "Flower Capsule",
         "Gems",
         "Gems",
         "Gold",
         "Gems",
         "Stardust",
         "Tickets",
         "Gems",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "Yellow Rider",
         "Stardust",
         "Gems",
         "Gold",
         "Gems",
         "Flower Capsule",
         "Gems",
         "EXP III",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gold",
         "Gems",
         "Stardust",
         "Gems",
         "Tickets",
         "Gems",
         "Gold",
         "Ship Toy",
         "Gems",
         "Gems",
         "Flower Capsule",
         "Gems",
         "EXP IV",
         "Gems",
         "Gold",
         "Gems",
         "Gems",
         "Flower Capsule",
         "Stardust",
         "Stardust",
         "Gems",
         "Gems",
         "Gold",
         "Flower Capsule",
         "Stardust",
         "Gems",
         "Stardust",
         "Gold",
         "Gems",
         "Flower Capsule",
         "Gold",
         "Gems",
         "Gems",
         "Stardust",
         "Gems",
         "EXP IV",
         "Gems",
         "Jozu",
         "Gems",
         "Gold",
         "Gold",
         "Gems",
         "Gems",
         "Gems",
         "Gold",
         "Stardust",
         "Flower Capsule",
         "Gems",
         "Stardust",
         "Gems",
         "Gems",
         "Gol D. Roger"
      }
   }
}
